spring:
  application:
    name: ms-email

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ms-email
    username: postgres
    password: postgres

  mail:
    host: smtp.gmail.com
    port: 587
    username: mymotorcycleapp@gmail.com
    password: "Motor#cycle07"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
